from kokoro_link.application.services.feature_keys import (
    FEATURE_ADDRESS_PREFERENCE_OBSERVER,
    FEATURE_ARC_ADAPT,
    FEATURE_ARC_CONTINUATION_DRAFT,
    FEATURE_ARC_SCENE_WRITE,
    FEATURE_CARD_TRANSLATE,
    FEATURE_CHARACTER_CREATION_INTAKE,
    FEATURE_CHARACTER_DRAFT,
    FEATURE_CHARACTER_PERSONALITY_TYPE,
    FEATURE_CHAT,
    FEATURE_CHAT_ASSIST,
    FEATURE_EXPERIMENT_ANALYSIS,
    FEATURE_FUSION_STORY_CRITIC,
    FEATURE_GROUP_CRITIC_REVIEW,
    FEATURE_GROUP_DESCRIPTIONS,
    FEATURE_GROUP_LABELS,
    FEATURE_GROUP_MODEL_GUIDANCE,
    FEATURE_GROUP_MEMBERS,
    FEATURE_LABELS,
    FEATURE_IMAGE_RECOGNITION,
    FEATURE_MEMOIR_LOCALIZE,
    FEATURE_NOVELTY_GATE,
    FEATURE_PERSONA_CURIOSITY,
    FEATURE_PERSONA_PROJECTION,
    FEATURE_PROMPT_MATERIAL_DIGEST,
    FEATURE_REGISTER_PROFILE,
    FEATURE_GROUP_LIGHT_OBSERVERS,
    FEATURE_GROUP_MULTIMODAL_PERCEPTION,
    FEATURE_TO_GROUP,
    GLOBAL_FEATURE_KEYS,
    LLM_FEATURE_GROUP_KEYS,
)


def test_humanization_auxiliary_feature_keys_are_operator_routable() -> None:
    assert FEATURE_CHAT in GLOBAL_FEATURE_KEYS
    assert FEATURE_IMAGE_RECOGNITION in GLOBAL_FEATURE_KEYS
    assert FEATURE_ADDRESS_PREFERENCE_OBSERVER in GLOBAL_FEATURE_KEYS
    assert FEATURE_EXPERIMENT_ANALYSIS in GLOBAL_FEATURE_KEYS
    assert FEATURE_CHAT_ASSIST in GLOBAL_FEATURE_KEYS
    assert FEATURE_PERSONA_PROJECTION in GLOBAL_FEATURE_KEYS
    assert FEATURE_PERSONA_CURIOSITY in GLOBAL_FEATURE_KEYS
    assert FEATURE_CARD_TRANSLATE in GLOBAL_FEATURE_KEYS
    assert FEATURE_MEMOIR_LOCALIZE in GLOBAL_FEATURE_KEYS
    assert FEATURE_PROMPT_MATERIAL_DIGEST in GLOBAL_FEATURE_KEYS
    assert FEATURE_NOVELTY_GATE in GLOBAL_FEATURE_KEYS
    assert FEATURE_REGISTER_PROFILE in GLOBAL_FEATURE_KEYS
    assert FEATURE_CHARACTER_DRAFT in GLOBAL_FEATURE_KEYS
    assert FEATURE_CHARACTER_PERSONALITY_TYPE in GLOBAL_FEATURE_KEYS
    assert FEATURE_CHARACTER_CREATION_INTAKE in GLOBAL_FEATURE_KEYS
    assert FEATURE_ARC_SCENE_WRITE in GLOBAL_FEATURE_KEYS
    assert FEATURE_ARC_ADAPT in GLOBAL_FEATURE_KEYS
    assert FEATURE_ARC_CONTINUATION_DRAFT in GLOBAL_FEATURE_KEYS
    assert FEATURE_FUSION_STORY_CRITIC in GLOBAL_FEATURE_KEYS
    assert FEATURE_LABELS[FEATURE_ADDRESS_PREFERENCE_OBSERVER]
    assert FEATURE_LABELS[FEATURE_CHAT]
    assert FEATURE_LABELS[FEATURE_IMAGE_RECOGNITION]
    assert FEATURE_LABELS[FEATURE_EXPERIMENT_ANALYSIS]
    assert FEATURE_LABELS[FEATURE_CHAT_ASSIST]
    assert FEATURE_LABELS[FEATURE_PERSONA_PROJECTION]
    assert FEATURE_LABELS[FEATURE_PERSONA_CURIOSITY]
    assert FEATURE_LABELS[FEATURE_CARD_TRANSLATE]
    assert FEATURE_LABELS[FEATURE_MEMOIR_LOCALIZE]
    assert FEATURE_LABELS[FEATURE_PROMPT_MATERIAL_DIGEST]
    assert FEATURE_LABELS[FEATURE_NOVELTY_GATE]
    assert FEATURE_LABELS[FEATURE_REGISTER_PROFILE]
    assert FEATURE_LABELS[FEATURE_CHARACTER_DRAFT]
    assert FEATURE_LABELS[FEATURE_CHARACTER_PERSONALITY_TYPE]
    assert FEATURE_LABELS[FEATURE_CHARACTER_CREATION_INTAKE]
    assert FEATURE_LABELS[FEATURE_ARC_SCENE_WRITE]
    assert FEATURE_LABELS[FEATURE_ARC_ADAPT]
    assert FEATURE_LABELS[FEATURE_ARC_CONTINUATION_DRAFT]
    assert FEATURE_LABELS[FEATURE_FUSION_STORY_CRITIC]


def test_every_llm_feature_key_belongs_to_exactly_one_group() -> None:
    memberships = [
        feature_key
        for members in FEATURE_GROUP_MEMBERS.values()
        for feature_key in members
    ]

    assert set(FEATURE_TO_GROUP) == set(GLOBAL_FEATURE_KEYS)
    assert set(memberships) == set(GLOBAL_FEATURE_KEYS)
    assert len(memberships) == len(set(memberships))


def test_feature_groups_have_complete_catalogue_metadata() -> None:
    assert set(FEATURE_GROUP_MEMBERS) == set(LLM_FEATURE_GROUP_KEYS)
    assert set(FEATURE_GROUP_LABELS) == set(LLM_FEATURE_GROUP_KEYS)
    assert set(FEATURE_GROUP_DESCRIPTIONS) == set(LLM_FEATURE_GROUP_KEYS)
    assert set(FEATURE_GROUP_MODEL_GUIDANCE) == set(LLM_FEATURE_GROUP_KEYS)

    for group_key in LLM_FEATURE_GROUP_KEYS:
        assert FEATURE_GROUP_LABELS[group_key]
        assert FEATURE_GROUP_DESCRIPTIONS[group_key]
        assert FEATURE_GROUP_MODEL_GUIDANCE[group_key]
        assert FEATURE_GROUP_MEMBERS[group_key]

    for feature_key, group_key in FEATURE_TO_GROUP.items():
        assert feature_key in GLOBAL_FEATURE_KEYS
        assert group_key in LLM_FEATURE_GROUP_KEYS


def test_prompt_material_digest_and_register_profile_use_light_observer_group() -> None:
    assert FEATURE_TO_GROUP[FEATURE_PROMPT_MATERIAL_DIGEST] == FEATURE_GROUP_LIGHT_OBSERVERS
    assert FEATURE_TO_GROUP[FEATURE_REGISTER_PROFILE] == FEATURE_GROUP_LIGHT_OBSERVERS


def test_reply_quality_gate_uses_critic_review_group() -> None:
    assert FEATURE_TO_GROUP[FEATURE_NOVELTY_GATE] == FEATURE_GROUP_CRITIC_REVIEW


def test_image_recognition_uses_multimodal_perception_group() -> None:
    assert FEATURE_TO_GROUP[FEATURE_IMAGE_RECOGNITION] == FEATURE_GROUP_MULTIMODAL_PERCEPTION
